### ISSUE TITLE
Drop dependency on env_logger

### ISSUE THREAD

**Issue by bluss** [BurntSushi/quickcheck#142]
env_logger pulls in regex, which is quite a lot to compile for a project where you just want smart tests.

I consider it normal to use quickcheck everywhere, just like I have benchmarks everywhere. If quickcheck is in the project, all of regex must be compiled in release mode as well to run benchmarks. For this reason I think the current deps are too large.

**Comment by BurntSushi** [comment]
I am in principle not opposed to this. I know I can't remember the last time I use this particular feature of `quickcheck`. I think I put the log output there because Haskell's QuickCheck showed it and it was fun to look at. But I've since been bad about setting `RUST_LOG`, and it turns out that I don't really miss the output.

How do others feel?

(My other impression is that `quickcheck` itself takes quite a long time to compile, so I wonder how much removing `regex` will help in practice on multicore systems.)

**Comment by bluss** [comment]
I agree with you about fun log messages. I noticed regex is an optional dep of env_logger, and forgot that quickcheck could make env_logger optional as well (instead of removing it), even opt-out. Either way is fine for me.

Maybe quickcheck takes a long time to compile, but at least it has good use.
