### ISSUE TITLE
Recursive shrink implementation requiring Clone on sub-iterators.

### ISSUE THREAD

**Issue by cristicbz** [BurntSushi/quickcheck#93]
Ok, so my problem is wanting to implement `shrink()` for a type made up of other `Arbitrary` types:

```rust
struct Foo {
    bar: Bar,
    baz: Baz,
}

impl Arbitrary for Foo {
    fn arbitrary<G: Gen>(gen: &mut Gen) -> Foo {
        Foo {
            bar: Bar::arbitrary(),
            baz: Baz::arbitrary(),
        }
    }

    fn shrink(&self) -> Box<Iterator<Item=Foo>> {
        let bars = self.bar.shrink().chain(Some(self.bar));
        let bazs = self.baz.shrink().chain(Some(self.baz));
        Box::new(bars.cartesian_product(bazs).map(|(bar, baz)| Foo { bar: bar, baz: baz }))
    }
}
```

I think this `shrink()` impl is very elegant, but it doesn't work because `cartesian_product` (from `itertools`) requires `Clone` on the second iterator (of course). This is a well known problem with trait objects; making `shrink()` return `Box<Iterator + Clone>` isn't a very satisfying solution, since there's a question of "where do I stop? what about `Sync + Send` etc?`. Furthermore, closures are never `Clone` :(. Making the iterator type of shrink an associated type

```rust
pub trait Arbitrary {
  type Shrink: Iterator<Item=Self>;
  fn shrink(&self) -> Self::Shrink;
  /* ... */
}
```

means a default impl can't be provided (at least not without specialisation), but it would solve the issue. I know I can implement a shrink iterator by storing `bar` and `baz` itself, and creating new iterators all the time, but that is a lot of boilerplate. Is there some general solution to this problem of composing `Arbitrary` types?

**Comment by cristicbz** [comment]
I rattled my brain for the better part of a day, and of course the moment I file the issue I figure it out. This library is so cool, the solution is really simple for everyone seeing this in future:
```rust
fn shrink(&self) -> Box<Iterator<Item=Foo>> {
    Box::new((self.bar.clone(), self.baz.clone()).shrink().map(|(bar, baz)| Foo { bar: bar, baz: baz }))
}
```

Boom! Tuples FTW!

**Comment by BurntSushi** [comment]
Glad you got it figured out. Indeed, falling back to tuple implementations of Arbitrary is a key trick in the Haskell quickcheck library too. It is also useful when you want to test properties with more than four parameters (or otherwise add more impls of Testable, but that's a pain).

Using an associated type isn't really tenable, I think. As you said, you can't provide a default impl. More than that, it makes shrinkers tedious to write, because you have to write out the concrete iterator types, which is, in my experience, quite laborious.
